#!/bin/bash
# Setup for Ubuntu machines (all others install stockfish as appropriate)

sudo apt install virtualenv
sudo apt install stockfish
virtualenv -p $1 .venv
$PWD/.venv/bin/activate
python3 -m pip install --upgrade pip
pip install -r $PWD/requirements.txt
