#!/bin/bash
# Setup for Ubuntu machines (all others install stockfish as appropriate)

sudo apt install virtualenv
sudo apt install stockfish
virtualenv .venv
. $PWD/.venv/bin/activate
pip install -r $PWD/requirements.txt
