name: machine learning chess engine
on: push

jobs:
    build:
        name: build and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: install python 3
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8.10
            - name: install dependencies
              run: |
                  python -m pip install --upgrade pip
                  sudo ./setup
            - name: run tests
              run: ./test
